language: node_js
node_js:
  - "5.2"

#whitelist
branches:
    only:
      - master

services:
    #enable docker service inside travis
    - docker

before install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"

script:
  #build the image
  - docker build --no-cache -t edwinrodriguez/jobfinder-repo .
  #tag the build
  - docker tag edwinrodriguez/jobfinder-repo:latest
  #push the image to the repository
  - docker push edwinrodriguez/jobfinder-repo
