language: node_js
node_js:
  - "5.2"

#whitelist
branches:
    only:
      - master

services:
    #enable docker service inside travis
    - docker

script:
  #login into docker
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
  #export global variables
  - export REPO=edwinrodriguez/jobfinder-repo
  #build the image
  - docker build --no-cache -t $REPO .
  #tag the build
  - docker tag $REPO:latest $REPO:v1
  #push the image to the repository
  - docker push $REPO
